### ISSUE TITLE
Rename default output file name to "tags"?

### ISSUE THREAD

**Issue by osa1** [dan-t/rusty-tags#55]
rusty-tags currently uses `rusty-tags.vi` name when generating tags for vim, but
that file name is not what vim looks for then looking for tags. It looks for a
file with name "tags" (and maybe a few other files?), so generating a "tags"
file would be better as currently we have to rename the generated file always.

An alternative would be to add a command line parameter for output file name,
but simply generating a "tags" file would be much more convenient.

**Comment by dan-t** [comment]
Please read the configuration section of the README howto
set an other name for the tags files.

But I don't quite understand why you have to rename the tags file
instead of just adding it with `set tags` to your `.vimrc`. If you want
tags for the Rust std library you already have to call `set tags`.

I'm not gonna change the default names, because clear different
names for the vi and emacs tags allow to have both at the same time,
which option I don't want to loose.

**Comment by osa1** [comment]
I didn't know rusty-tags has a config file now. I think it didn't when I first
started using it, and I've never checked the README file since then.

If you're not going to change it then this can be closed.

This is mostly about the UX. It's possible to make this work for vim and emacs
users with 0 configuration on either sides (the editor or rust-tags), which IMO
provides better UX. I have more than enough config files already so I prefer not
creating yet another one for rusty-tags, I also don't want yet another line in
my 373-line vimrc.

As an example, `fast-tags` does this right. On any system I can just do `cabal
install fast-tags` and it works perfectly.

**Comment by dan-t** [comment]
> As an example, fast-tags does this right. On any system I can just do cabal install fast-tags and it works perfectly.

Like I already said, you can't have tags for the Rust std library that way. By design
the std tags aren't merged into the cargo project tags, which makes it
easier to switch compiler versions and just get the right tags.

Breaking the backward compatibility for all other users at this point in
time doesn't make any sense.

**Comment by dan-t** [comment]
I have just merged a PR that adds an ˋ—outputˋ option, to name the tags file.
