### ISSUE TITLE
tags for rust standard library not generated

### ISSUE THREAD

**Issue by albertopatino** [dan-t/rusty-tags#75]
Hi, 

After install rusty-tags from cargo install or from this Git repo with cargo build I use the rusty-tags  setting RUST_SRC_PATH env variable. 

From verbose mode I see 

```
❯ rusty-tags --force-recreate --verbose  vi
Switching to single threaded for verbose output
Using configuration: vi_tags='rusty-tags.vi', emacs_tags='rusty-tags.emacs', ctags_exe='Some("/home/albertop/GitHub/ctags/ctags")', ctags_options=''
Found ctags executable: UniversalCtags("/home/albertop/GitHub/ctags/ctags")
Fetching source and metadata ...
Creating tags for the standard library ...

Creating tags ...
   with command: "/home/albertop/GitHub/ctags/ctags" "--recurse" "--languages=Rust" "-o" "/home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/.tmpflvfrb"

   for source:

   cached at:
      /home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/.tmpflvfrb

Move tags ...
   from:
      /home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/.tmpflvfrb
   to:
      /home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rusty-tags.vi
Found package of (files, 0.1.0) with source at '/home/albertop/Dev/rust/files/src'
Found workspace members: [(files, 0.1.0)]
Building tree for (files, 0.1.0)
Creating tags for: files ...

```

Tags for cargo project are ok but not for standard library.

Workaround is to run ctags under $RUST_SRC_PATH manually.

**Comment by dan-t** [comment]
Hi Alberto,

in which way aren't they generated?

Doesn't '/home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rusty-tags.vi'
contain any tags?

Can't you access tags of the standard library in vim?

Does your vim tags setting contain $RUST_SRC_PATH, like described in the README:
autocmd BufRead *.rs :setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi

Greetings,
Daniel

**Comment by albertopatino** [comment]
Hi Daniel,
Thanks for follow-up and sorry for late reply, this is the first time I report something in GitHub.

Answering your first question:

Q.- Doesn't '/home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rusty-tags.vi'
contain any tags? 

A.- Exactly, that is the issue, running rusty-tags from command line as instructions located in rust base project generates almost empty rusty-tags: ( I renamed to rusty-tags.wrong 516 Bytes only)

❯ echo $RUST_SRC_PATH
/home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library

❯ pwd
/home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library

❯ ls -lrt
  rwxr-xr-x  5  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    alloc/
  rwxr-xr-x  5  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    core/
  rwxr-xr-x  3  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    test/
  rwxr-xr-x  8  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    backtrace/
  rwxr-xr-x  3  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    term/
  rwxr-xr-x  5  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    std/
  rwxr-xr-x  3  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    panic_unwind/
  rwxr-xr-x  3  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    unwind/
  rwxr-xr-x  2  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    rtstartup/
  rwxr-xr-x  2  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    rustc-std-workspace-alloc/
  rwxr-xr-x  4  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    proc_macro/
  rwxr-xr-x  2  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    rustc-std-workspace-core/
  rwxr-xr-x  3  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    panic_abort/
  rwxr-xr-x  2  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    rustc-std-workspace-std/
  rwxr-xr-x  3  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    profiler_builtins/
  rwxr-xr-x  6  albertop  albertop     4 KiB  Sun Oct 11 22:04:00 2020    stdarch/
  rw-r--r--  1  albertop  albertop     3 MiB  Tue Oct 13 22:58:28 2020    rusty-tags.vi
  rw-------  1  albertop  albertop   514 B    Tue Oct 13 22:51:22 2020    rusty-tags,wrong  rw-r--r--  1  albertop  albertop     3 MiB  Tue Oct 13 22:58:14 2020    tags

Then when running rusty-tags from $RUST_SRC_PATH rusty-tags.vi 3MB apparently is correctly generated.

But then when using this rusty-tags.vi file I see a wrong behaviour, from a simple rs file I go to push definition from Vec using Neovim and Visual Studio Code, but from Neovim using rusty-tags I get push() definicion from slice.rs file. Same test in VS Code I get push() definition from vec.rs file.

From my .nvimrc:

  274 autocmd BufRead *.rs :setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi
  275
  276 autocmd BufWritePost *.rs :silent! exec "!rusty-tags vi --quiet --start-dir=" . expand('%:p:h') . "&" | redraw!

Screenshots  [here](http://albertopatino.com.mx/?p=295)

Please let me know if you need more info.

Thanks

**Comment by dan-t** [comment]
Hi Alberto,

> ❯ echo $RUST_SRC_PATH
> /home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library

that path doesn't look right.

dan@octa ~> echo $RUST_SRC_PATH 
/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/

dan@octa ~> ls -la /home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library
ls: cannot access '/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library': No such file or directory

> But then when using this rusty-tags.vi file I see a wrong behaviour, from a simple rs file I go to push definition from
> Vec using Neovim and Visual Studio Code, but from Neovim using rusty-tags I get push() definicion from slice.rs file.
> Same test in VS Code I get push() definition from vec.rs file.

If there're multiple 'push' methods defined, then tags - by definition -
can't jump to the right place, because there's no type information. The
'push' symbol is just looked up in the tags file and the first found
definition is used. Your editor has a shortcut to go through all the 'push'
definitions.

Looking inside of my 'rusty-tags.vi' file for $RUST_SRC_PATH and
searching for lines starting with 'push', I see:

push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/benches/slice.rs	/^fn push(b: &mut Bencher) {$/;"	f
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/collections/binary_heap.rs	/^    pub fn push(&mut self, item: T) {$/;"	P	implementation:BinaryHeap
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/collections/btree/node.rs	/^    pub fn push(&mut self, key: K, val: V) {$/;"	P	implementation:NodeRef
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/collections/btree/node.rs	/^    pub fn push(&mut self, key: K, val: V, edge: Root<K, V>) {$/;"	P	implementation:NodeRef
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/string.rs	/^    pub fn push(&mut self, ch: char) {$/;"	P	implementation:String
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs	/^    pub fn push(&mut self, value: T) {$/;"	P	implementation:Vec
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/ffi/os_str.rs	/^    pub fn push<T: AsRef<OsStr>>(&mut self, s: T) {$/;"	P	implementation:OsString
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/path.rs	/^    pub fn push<P: AsRef<Path>>(&mut self, path: P) {$/;"	P	implementation:PathBuf
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/mpsc/mpsc_queue.rs	/^    pub fn push(&self, t: T) {$/;"	P	implementation:Queue
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/mpsc/spsc_queue.rs	/^    pub fn push(&self, t: T) {$/;"	P	implementation:Queue
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys/sgx/waitqueue.rs	/^        pub unsafe fn push<'a>(&mut self, entry: &'a mut UnsafeListEntry<T>) -> &'a T {$/;"	P	implementation:unsafe_list::UnsafeList
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys/unix/process/process_common.rs	/^    pub fn push(&mut self, item: CString) {$/;"	P	implementation:CStringArray
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys/vxworks/process/process_common.rs	/^    pub fn push(&mut self, item: CString) {$/;"	P	implementation:CStringArray
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/at_exit_imp.rs	/^pub fn push(f: Box<dyn FnOnce()>) -> bool {$/;"	f
push	/home/dan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/wtf8.rs	/^    pub fn push(&mut self, code_point: CodePoint) {$/;"	P	implementation:Wtf8Buf

So the first one is from 'slice.rs', I don't know why 'Visual Studio Code'
takes the one from 'vec.rs'.

Greetings,
Daniel

**Comment by albertopatino** [comment]
Hi Daniel, 

I see  your point, I used 'library' directory instead of 'src' because I have this layout in my rust installation:

❯ pwd
/home/albertop/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust

❯ ls src
      llvm-project/      rusty-tags.vi

❯ ls library
      alloc/                  rtstartup/                      test/
      backtrace/              rustc-std-workspace-alloc/      unwind/
      core/                   rustc-std-workspace-core/       rusty-tags.vi
      panic_abort/            rustc-std-workspace-std/  
      panic_unwind/           std/                            tags
      proc_macro/             stdarch/
      profiler_builtins/      term

I don''t know why my folder structure for Rust Library looks different to yours. If I update my RUST_SRC_PATH to point to src things still not working as rusty-tags expects differnet layout.

I appreciate for your help. I have the workaround working, I just wanted to clarify this issue for other users trying to use rusty-tags.

Thanks and regards,
Alberto P

**Comment by albertopatino** [comment]
Will check my environment, as it looks something is wrong with it.

**Comment by albertopatino** [comment]
Will check my environment, as it looks something is wrong with it.

**Comment by dan-t** [comment]
Hi Alberto,

for whatever reason there seems to be a difference in the source for the
stable and nightly toolchain. I'm trying to get some infos why that's
the case. For now only the source layout of the stable toolchain is
supported.

Greetings,
Daniel

**Comment by dan-t** [comment]
Ok, here's the explanation: https://www.reddit.com/r/rust/comments/jf92en/rustup_rustsrc_for_toolchains_stable_and_nightly/g9j5xfl/

**Comment by albertopatino** [comment]
Thanks a lot for follow up and investigation from your side. I'm wondering how this didn't come up before :-) as I'm really new to Rust. I was wondering why your source code was looking at directories with not much sense to me. 

Great feedback Dan. 
Sincerely,
Alberto Patino

**Comment by dan-t** [comment]
On Sun, Oct 25, 2020 at 09:40:01PM -0700, Alberto Patino wrote:
> Thanks a lot for follow up and investigation from your side. I'm
> wondering how this didn't come up before :-) as I'm really new to
> Rust. I was wondering why your source code was looking at directories
> with not much sense to me.

If you're new to rust and don't have a particular reason to use the
nightly compiler version, then I can only recommend to you to use the
stable compiler version. 

You will most likely run into less issues.

**Comment by dan-t** [comment]
rusty-tags 3.8.0 should now solve the issue and you can now use:

    export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/library/
